### ISSUE TITLE
Support for validating OpenAPI 3 spec

### ISSUE THREAD

**Issue by Teraskull** [overflowdigital/Flask-OpenAPI#23]
Currently nothing happens if I try validating a v3 schema.

**Comment by katerinatiddy** [comment]
Thanks for reporting @Teraskull 

We'll start looking into this and adding some better testing for the future.

**Comment by joshuathompsonlindley** [comment]
Sorry for the inactivity. We're still looking at rehauling our validation code and are currently aiming to ship this, with v2 improvements towards the end of February!
